name: MSYS2 Autotools Build
# msys2 build for The Sword.Patched Project
on:
  # push:
  #  branches: [ "master" ]
  # pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
#  schedule:
#    - cron: 0 17 * * *

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟦', sys: mingw64, package_prefix: mingw-w64-x86_64 }
          - { icon: '🟨', sys: ucrt64, package_prefix: mingw-w64-ucrt-x86_64 } 
    defaults:
      run:
        # This is critical: it tells the runner to execute the following 
        # commands inside the MSYS2 shell (UCRT64) rather than PowerShell/CMD.
        shell: msys2 {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        # Install core build tools and compilers        
        install: >-
          base-devel
          git
          make
          autoconf
          automake
          libtool
          python3
          pkg-config
          zip
          binutils
        pacboy: >-
          zlib:x
          bzip2:x
          xz:x
          icu:x
          curl:x
          clucene:x          
          xapian-core:x
          gcc:p       
    - run: gcc --version

    - name: '️#️⃣ get-hash'
      id: hash
      run: echo "sha_short=$(git describe --tags)" >> $GITHUB_OUTPUT  

    - name: Generate Configure Script (Autoreconf)
      # Run this if your repo stores configure.ac/am but not the generated 'configure' script
      run: ./autogen.sh  # autoreconf -fiv

    - name: '🔧 Configure Project' 
      # Add any configure flags here (e.g., --enable-debug)
      run: ./configure --with-cxx11regex --with-cxx11time --with-bzip2 --with-xz # CXXFLAGS="-Dstricmp=_stricmp"  'CXXFLAGS=-g -O2 -static'

    - name: Upload config.log
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: config.log
        path: config.log
        
    - name: '🚧 Build and install jbig2enc'
      run: |
           # make LDFLAGS="-all-static"
           make
           make install  
      
    - name: '⏫ Upload Build Results'
      uses: actions/upload-artifact@v7
      with:
        name: sword_${{ steps.hash.outputs.sha_short }}-${{matrix.sys}}
        path: sword__${{ steps.hash.outputs.sha_short }}-${{matrix.sys}}.zip
        retention-days: 5       

    - name: Run Tests (Optional)
      run: make check
