name: cmake-win64
runs-on: windows-latest
steps:
  - uses: ilammy/setup-nasm@v1.5
  - uses: microsoft/setup-msbuild@v3
  - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
    uses: actions/checkout@v7
